"""
Cost/latency dashboard (run from .venv-phoenix): exports
reports/dashboard_data.csv (the exact data behind the chart, per the
spec) and reports/dashboard.png rendered from it.

Honesty note: this PNG is generated by this script from the exported
Phoenix span data — it is not a literal screenshot of the Phoenix web
UI (localhost:6006), which this non-interactive environment cannot
open a browser to capture. The underlying data is identical either
way. To capture the literal Phoenix UI screenshot the spec also
describes, run the Phoenix server (scripts/start_phoenix_server.py),
open http://localhost:6006 in a browser, and screenshot its latency/
cost/token dashboard alongside this file.

    ./.venv-phoenix/bin/python scripts/build_dashboard.py
"""

from __future__ import annotations

import pathlib

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SPANS_PATH = REPO_ROOT / "traces" / "phoenix_spans.parquet"
CSV_OUT = REPO_ROOT / "reports" / "dashboard_data.csv"
PNG_OUT = REPO_ROOT / "reports" / "dashboard.png"


def main() -> None:
    if not SPANS_PATH.exists():
        raise SystemExit(f"{SPANS_PATH} not found — run scripts/export_phoenix_traces.py first.")

    df = pd.read_parquet(SPANS_PATH)
    df["latency_ms"] = (df["end_time"] - df["start_time"]).dt.total_seconds() * 1000
    kind_col = "attributes.openinference.span.kind"

    CSV_OUT.parent.mkdir(parents=True, exist_ok=True)
    cols = [c for c in ["name", kind_col, "start_time", "end_time", "latency_ms"] if c in df.columns]
    df[cols].to_csv(CSV_OUT, index=False)
    print(f"Wrote {CSV_OUT}")

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    by_kind = df.groupby(kind_col)["latency_ms"].mean().sort_values(ascending=False) if kind_col in df.columns else pd.Series()
    axes[0].bar(by_kind.index.astype(str), by_kind.values, color="#4C72B0")
    axes[0].set_title("Mean latency by span kind")
    axes[0].set_ylabel("latency (ms)")
    axes[0].tick_params(axis="x", rotation=20)

    tool_df = df[df[kind_col] == "TOOL"] if kind_col in df.columns else df.iloc[0:0]
    by_tool = tool_df.groupby("name")["latency_ms"].mean().sort_values(ascending=False)
    axes[1].bar(by_tool.index.astype(str), by_tool.values, color="#55A868")
    axes[1].set_title("Mean latency by tool")
    axes[1].set_ylabel("latency (ms)")
    axes[1].tick_params(axis="x", rotation=30)

    fig.suptitle("Dispute Copilot — Latency Dashboard (from exported Phoenix spans)")
    fig.tight_layout()
    fig.savefig(PNG_OUT, dpi=150)
    print(f"Wrote {PNG_OUT}")


if __name__ == "__main__":
    main()
